apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: zqadmin
  POSTGRES_PASSWORD: VerySuperStrong7056778276!!!@@@
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: zquser
  POSTGRES_NON_ROOT_PASSWORD: NotVerySuperStrong7056778276@@@!!!
